project: 
  type: website
  output-dir: docs

website:
  title: "Marco Reina Data Analysis Project"
  navbar:
    left:
      - text: "EDA analysis"
        file: code/eda-code/01_eda.html
      - text: "Descriptive Analysis"
        file: code/analysis-code/02_descriptive-analysis.qmd
      - text: "Modeling"
        file: code/analysis-code/03_model-fitting.qmd
    right:
      - icon: github 
        href: https://github.com/reinaantillon/marcoreina-MADA-project
format:
  html:
    theme: lux
    highlight: zenburn
    css: styles.css
    toc: FALSE