project: 
  type: website
  output-dir: docs

website:
  title: "Marco Reina MADA Project"
  navbar:
    left:
      - text: "EDA analysis"
        file: code/eda-code/01_eda.html
      - text: "Descriptive Analysis"
        file: code/analysis-code/02_descriptive-analysis.qmd
      - text: "Linear Model"
        file: code/analysis-code/03_model-fitting.qmd
      - text: "Random Forest"
        file: code/analysis-code/04_random-forest.qmd
      - text: "Cross Validation"
        file: code/analysis-code/05_cross-validation.qmd
      - text: "Manuscript"
        file: products/manuscript/Manuscript.qmd
    right:
      - icon: github 
        href: https://github.com/reinaantillon/marcoreina-MADA-project
format:
  html:
    theme: lux
    highlight: zenburn
    css: styles.css
    toc: FALSE